M48
; DRILL file KiCad 10.0.1 date 2026-05-25T23:06:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-25T23:06:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X164.242Y-88.242
X170.022Y-88.242
T2
X168.8Y-57.1
X168.8Y-79.5
M30
